#
# Module manifest for module 'hMailDsc'
#
# Generated by: Nik Charlebois
#
# Generated on: 2018/03/12
#

@{

    # Script module or binary module file associated with this manifest.
    # RootModule = ''
    
    # Version number of this module.
    ModuleVersion = '1.0.0.0'
    
    # ID used to uniquely identify this module
    GUID = 'ef9a065f-8a6e-4734-8635-39089e45416e'
    
    # Author of this module
    Author = 'Nik Charlebois'
    
    # Company or vendor of this module
    CompanyName = ''
    
    # Copyright statement for this module
    Copyright = 'Nik Charlebois'
    
    # Description of the functionality provided by this module
    Description = 'The hMailDsc module provides the ability to install and configure hMail Server.'
    
    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '4.0'
    
    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''
    
    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''
    
    # Minimum version of Microsoft .NET Framework required by this module
    # DotNetFrameworkVersion = ''
    
    # Minimum version of the common language runtime (CLR) required by this module
    # CLRVersion = ''
    
    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''
    
    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()
    
    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()
    
    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()
    
    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()
    
    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()
    
    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules = @("modules\hMailDSC.Util\hMailDSC.Util.psm1")
    
    # Functions to export from this module
    # FunctionsToExport = '*'
    
    # Cmdlets to export from this module
    CmdletsToExport = @("Get-hMailInstalledLocation",
                        "Test-hMailDscParameterState",
                        "Test-hMailDSCObjectHasProperty")
    
    # Variables to export from this module
    # VariablesToExport = '*'
    
    # Aliases to export from this module
    # AliasesToExport = '*'
    
    # List of all modules packaged with this module
    # ModuleList = @()
    
    # List of all files packaged with this module
    # FileList = @()
    
    # Private data to pass to the module specified in RootModule/ModuleToProcess
    # PrivateData = ''
    
    # HelpInfo URI of this module
    # HelpInfoURI = ''
    
    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''
    
    PrivateData = @{
    
        PSData = @{
    
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('DesiredStateConfiguration', 'DSC', 'DSCResource')
    
            # A URL to the license for this module.
            LicenseUri = 'https://github.com/NikCharlebois/hMailDsc/blob/master/LICENSE'
    
            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/NikCharlebois/hMailDsc'
    
            # A URL to an icon representing this module.
            #IconUri = 'https://github.com/Microsoft/WorkflowManagerDSC/blob/master/Images/DSCModuleLogo.png?raw=true'
    
            # ReleaseNotes of this module
            ReleaseNotes = '* Initial Release;'
    
        } # End of PSData hashtable
    
    } # End of PrivateData hashtable
    
    }
    
    